name: Error test

on:
  workflow_dispatch:

env:
  NODE_VERSION: '16'

defaults:
  run:
    shell: bash

jobs:

  errorTest:
    name: errorTestJob
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4

     - uses: ./error_test_action

     - name: error log
       run: |
            text="This is error1\nThis is error2"
            text="${text//'\n'/'%0A'}" #replace '\n' with '%0A'
            echo $text
            echo "::error file=app.js,line=10,col=15::$text"
