name: Build and Test

on:
  pull_request:
    branches:
      - master
  check_run:
    types: [rerequested, requested_action]
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:

env:
  NODE_VERSION: '16'

defaults:
  run:
    shell: bash

jobs:

  lintExtension:
    name: Lint Extension
    runs-on: ubuntu-latest
    # if: github.repository == 'julia-vscode/julia-vscode'
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      # - run: npm i -D @actions/core
      # - run: npm i -D @actions/github
      # - run: npm i -D @octokit/core
      # - run: npm i -D @octokit/plugin-paginate-rest
      # - run: npm i -D @octokit/webhooks

      # - name: Verify linting is turned on for changed files
      #   uses: ./.github/actions/modified-files
      #   id: modified-folders

      # - name: Dump
      #   run: echo "${{steps.modified-folders.outputs.modifiedRootFolders}}"

      - run: npx eslint -c .eslintrc.json --ext .ts src

      # - name: Run prettier on TypeScript code
      #   run: npx prettier 'src/**/*.ts*' --check

      # - name: Run prettier on JavaScript code
      #   run: npx prettier 'build/**/*.js' --check

  testExtension:
    name: Test Extension
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        julia_version: [1.6]
    if: github.repository == 'julia-vscode/julia-vscode'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{matrix.julia_version}}

      - run: npm ci

      - run: npm run compile

      - name: Set xvfb parameters linux
        if: matrix.os == 'ubuntu-latest'
        run: echo "xvfbCommand=--server-args=\"-screen 0 1024x768x24\"" >> $GITHUB_ENV

      - name: Run tests
        if: matrix.os == 'ubuntu-latest'
        env:
          DISPLAY: 10
        uses: GabrielBB/xvfb-action@v1.4
        with:
          run: npm run test

      - name: Run tests
        if: matrix.os == 'macos-latest' || matrix.os == 'windows-latest'
        run: npm run test

  testJuliaPackages:
    name: Test Julia Packages
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        julia_version: ['1.0', 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8]
    if: github.repository == 'julia-vscode/julia-vscode'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{matrix.julia_version}}

      - name: 'Run the Julia tests'
        run: |
          julia -e 'using InteractiveUtils; versioninfo()'
          julia --project=./scripts/environments/languageserver/v${{matrix.julia_version}} -e 'using Pkg; Pkg.resolve()'
          julia --project=./scripts/environments/languageserver/v${{matrix.julia_version}} -e 'using Pkg; Pkg.test("CSTParser", coverage=true)'
          julia --project=./scripts/environments/languageserver/v${{matrix.julia_version}} -e 'using Pkg; Pkg.test("JSONRPC", coverage=true)'
          julia --project=./scripts/environments/languageserver/v${{matrix.julia_version}} -e 'using Pkg; Pkg.test("LanguageServer", coverage=true)'
          julia --project=./scripts/environments/languageserver/v${{matrix.julia_version}} -e 'using Pkg; Pkg.test("StaticLint", coverage=true)'
          julia --project=./scripts/environments/languageserver/v${{matrix.julia_version}} -e 'using Pkg; Pkg.test("SymbolServer", coverage=true)'
          julia --project=./scripts/testenvironments/debugadapter/v${{matrix.julia_version}} -e 'using Pkg; Pkg.test("DebugAdapter", coverage=true)'
          julia --project=./scripts/testenvironments/vscodedebugger/v${{matrix.julia_version}} -e 'using Pkg; Pkg.test("VSCodeDebugger", coverage=true)'
          julia --project=./scripts/testenvironments/vscodeserver/v${{matrix.julia_version}} -e 'using Pkg; Pkg.test("VSCodeServer", coverage=true)'

  buildReleaseVSIX:
    name: Build Release VSIX
    runs-on: ubuntu-latest
    # if: github.repository == 'julia-vscode/julia-vscode'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}

      - run: npm ci

      - run: npm run package

      - uses: actions/upload-artifact@v2
        with:
          name: release-vsix
          path: '*.vsix'

  buildInsiderVSIX:
    name: Build Insider VSIX
    runs-on: windows-latest
    # if: github.repository == 'julia-vscode/julia-vscode'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Modify package.json
        shell: pwsh
        run: |
          $package = Get-Content package.json | ConvertFrom-Json
          $package.description = "Julia Language Support (Insider)"
          $package.displayName = "Julia Insider"
          $package.name ="language-julia-insider"
          $package.preview = $TRUE
          $package | ConvertTo-Json -Depth 100 | Out-File package.json
          Move-Item -Force README-insider.md README.md

      - run: npm ci

      - run: npm run package

      - uses: actions/upload-artifact@v2
        with:
          name: insider-vsix
          path: '*.vsix'

  deployInsiderVSCMarketplace:
    name: Deploy Insider to VS Code Marketplace
    needs: [lintExtension, testExtension, testJuliaPackages, buildInsiderVSIX]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment: insider-channel
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: insider-vsix
          path: .
      - name: Find filename
        shell: pwsh
        run: |
          $filename =  (Get-ChildItem *.vsix)[0].FullName
          echo "PACKAGE_FILENAME=$($filename)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Publish package
        env:
          MARKET_KEY: ${{secrets.VSCEKEY}}
        run: |
          npm install -g vsce
          vsce publish -p $MARKET_KEY --packagePath $PACKAGE_FILENAME

  deployInsiderOVSXMarketplace:
    name: Deploy Insider to Open VSX Marketplace
    needs: [lintExtension, testExtension, testJuliaPackages, buildInsiderVSIX]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment: insider-channel
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: insider-vsix
          path: .
      - name: Find filename
        shell: pwsh
        run: |
          $filename =  (Get-ChildItem *.vsix)[0].FullName
          echo "PACKAGE_FILENAME=$($filename)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Publish package
        env:
          MARKET_KEY: ${{secrets.OVSXKEY}}
        run: |
          npx ovsx publish $PACKAGE_FILENAME -p $MARKET_KEY

  deployReleaseVSCMarketplace:
    name: Deploy Release to VS Code Marketplace
    needs: [lintExtension, testExtension, testJuliaPackages, buildReleaseVSIX]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment: release-channel
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: release-vsix
          path: .
      - name: Find filename
        shell: pwsh
        run: |
          $filename =  (Get-ChildItem *.vsix)[0].FullName
          echo "PACKAGE_FILENAME=$($filename)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Publish package
        env:
          MARKET_KEY: ${{secrets.VSCEKEY}}
        run: |
          npm install -g vsce
          vsce publish -p $MARKET_KEY --packagePath $PACKAGE_FILENAME

  deployReleaseOVSXMarketplace:
    name: Deploy Release to Open VSX Marketplace
    needs: [lintExtension, testExtension, testJuliaPackages, buildReleaseVSIX]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment: release-channel
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: release-vsix
          path: .
      - name: Find filename
        shell: pwsh
        run: |
          $filename =  (Get-ChildItem *.vsix)[0].FullName
          echo "PACKAGE_FILENAME=$($filename)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Publish package
        env:
          MARKET_KEY: ${{secrets.OVSXKEY}}
        run: |
          npx ovsx publish $PACKAGE_FILENAME -p $MARKET_KEY

  deployInsiderGitHub:
    name: Deploy Insider to GitHub Release
    needs: [lintExtension, testExtension, testJuliaPackages, buildInsiderVSIX]
    if: startsWith(github.ref, 'refs/tags/')
    environment: insider-channel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: insider-vsix
          path: .
      - name: Find filename
        shell: pwsh
        run: |
          $filename =  (Get-ChildItem *.vsix)[0].FullName
          echo "PACKAGE_FILENAME=$($filename)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{env.PACKAGE_FILENAME}}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deployReleaseGitHub:
    name: Deploy Release to GitHub Release
    needs: [lintExtension, testExtension, testJuliaPackages, buildReleaseVSIX]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment: release-channel
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: release-vsix
          path: .
      - name: Find filename
        shell: pwsh
        run: |
          $filename =  (Get-ChildItem *.vsix)[0].FullName
          echo "PACKAGE_FILENAME=$($filename)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{env.PACKAGE_FILENAME}}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-microprint:
          runs-on: ubuntu-latest

          needs: testExtension

          steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Get microprint of check-examples job logs
              uses: AlphaSteam/microprint-generator@v3
              with:
                  job_name: testExtension
                  microprint_filename: microprint
                  microprint_path: ./
                  microprint_config_path: ./
                  microprint_config_filename: config
                  microprint_visualizer_link_filename: microprint-visualizer
                  microprint_visualizer_link_path: ./

            - name: Pull Remote Changes
              run: git pull

            - name: Commit microprint
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: Updated microprint of check-examples job
